version: "3"
services:

  fabrik:
    image: postgres:14.2-alpine
    container_name: fabrik
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./init:/docker-entrypoint-initdb.d

